<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report History</title>
</head>
<body class="bg-gray-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <!-- Page Header -->
        <div class="mb-8">
            <h1 class="text-2xl font-bold text-gray-900">Report History</h1>
            <p class="mt-1 text-sm text-gray-500">Previously generated compliance reports</p>
        </div>

        <!-- Filters -->
        <div class="bg-white border border-[#e5e5e5] rounded-xl p-6 mb-6">
            <div class="flex flex-wrap gap-4">
                <select class="px-4 py-2 text-sm bg-white border border-[#e5e5e5] rounded-lg">
                    <option value="">All Report Types</option>
                    <option value="str">STR</option>
                    <option value="edd">EDD</option>
                </select>
                <select class="px-4 py-2 text-sm bg-white border border-[#e5e5e5] rounded-lg">
                    <option value="">All Status</option>
                    <option value="draft">Draft</option>
                    <option value="generated">Generated</option>
                    <option value="submitted">Submitted</option>
                    <option value="accepted">Accepted</option>
                </select>
                <input type="date" class="px-4 py-2 text-sm bg-white border border-[#e5e5e5] rounded-lg">
                <input type="date" class="px-4 py-2 text-sm bg-white border border-[#e5e5e5] rounded-lg">
                <button class="px-4 py-2 text-sm font-medium rounded-lg bg-[#0a0a0a] text-white hover:bg-[#262626]">
                    Filter
                </button>
            </div>
        </div>

        <!-- Reports Table -->
        <div class="bg-white border border-[#e5e5e5] rounded-xl overflow-hidden">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Report ID</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Type</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Period</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Branch</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Generated By</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Generated At</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                    <tr>
                        <td class="px-4 py-3 text-sm text-gray-900">RPT-2024-001</td>
                        <td class="px-4 py-3 text-sm text-gray-500">January 2024</td>
                        <td class="px-4 py-3 text-sm text-gray-900">Kuala Lumpur</td>
                        <td class="px-4 py-3 text-sm">
                            <span class="inline-flex px-2.5 py-0.5 text-xs font-medium rounded bg-green-100 text-green-700">Accepted</span>
                        </td>
                        <td class="px-4 py-3 text-sm text-gray-900">Jane Doe</td>
                        <td class="px-4 py-3 text-sm text-gray-500">2024-02-01 09:30</td>
                        <td class="px-4 py-3 text-sm">
                            <a href="#" class="text-blue-600 hover:text-blue-800">Download</a>
                        </td>
                    </tr>
                    <tr>
                        <td class="px-4 py-3 text-sm text-gray-900">RPT-2024-002</td>
                        <td class="px-4 py-3 text-sm text-gray-900">STR</td>
                        <td class="px-4 py-3 text-sm text-gray-500">December 2023</td>
                        <td class="px-4 py-3 text-sm text-gray-900">All Branches</td>
                        <td class="px-4 py-3 text-sm">
                            <span class="inline-flex px-2.5 py-0.5 text-xs font-medium rounded bg-blue-100 text-blue-700">Submitted</span>
                        </td>
                        <td class="px-4 py-3 text-sm text-gray-900">John Smith</td>
                        <td class="px-4 py-3 text-sm text-gray-500">2024-01-15 14:20</td>
                        <td class="px-4 py-3 text-sm">
                            <a href="#" class="text-blue-600 hover:text-blue-800">Download</a>
                        </td>
                    </tr>
                    <tr>
                        <td class="px-4 py-3 text-sm text-gray-900">RPT-2024-003</td>
                        <td class="px-4 py-3 text-sm text-gray-500">December 2023</td>
                        <td class="px-4 py-3 text-sm text-gray-900">Penang</td>
                        <td class="px-4 py-3 text-sm">
                            <span class="inline-flex px-2.5 py-0.5 text-xs font-medium rounded bg-yellow-100 text-yellow-700">Draft</span>
                        </td>
                        <td class="px-4 py-3 text-sm text-gray-900">Jane Doe</td>
                        <td class="px-4 py-3 text-sm text-gray-500">2024-01-10 11:00</td>
                        <td class="px-4 py-3 text-sm">
                            <a href="#" class="text-blue-600 hover:text-blue-800">Continue</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>