@extends('layouts.app')

@section('title', 'Report History')

@section('content')
<div class="p-6">
    <h1 class="text-2xl font-bold mb-6">Report History</h1>

    <div class="bg-white rounded-lg shadow">
        <table class="w-full">
            <thead class="bg-gray-50">
                <tr>
                    <th class="px-4 py-2 text-left text-sm">Type</th>
                    <th class="px-4 py-2 text-left text-sm">Status</th>
                    <th class="px-4 py-2 text-left text-sm">Generated By</th>
                    <th class="px-4 py-2 text-left text-sm">Generated At</th>
                    <th class="px-4 py-2 text-left text-sm">Duration</th>
                    <th class="px-4 py-2 text-left text-sm">Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                <tr class="border-b">
                    <td class="px-4 py-2">{{ strtoupper($report->report_type) }}</td>
                    <td class="px-4 py-2">
                        <span class="px-2 py-1 rounded text-xs font-medium
                            @if($report->status->value === 'completed') bg-green-100 text-green-700
                            @elseif($report->status->value === 'failed') bg-red-100 text-red-700
                            @elseif($report->status->value === 'running') bg-yellow-100 text-yellow-700
                            @else bg-blue-100 text-blue-700
                            @endif">
                            {{ $report->status->label() }}
                        </span>
                    </td>
                    <td class="px-4 py-2">{{ $report->generatedBy?->name ?? 'System' }}</td>
                    <td class="px-4 py-2">{{ $report->created_at->format('Y-m-d H:i') }}</td>
                    <td class="px-4 py-2">{{ $report->getDurationInSeconds() ? $report->getDurationInSeconds() . 's' : '-' }}</td>
                    <td class="px-4 py-2">
                        @if($report->status->value === 'completed' && $report->file_path)
                            <a href="{{ route('compliance.reporting.history.download', $report->id) }}" class="text-blue-600 hover:underline">Download</a>
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="px-4 py-8 text-center text-gray-500">No reports generated yet</td>
                </tr>
                @endforelse
            </tbody>
        </table>
        <div class="p-4">
            {{ $reports->links() }}
        </div>
    </div>
</div>
@endsection