<x-app-layout title="Reports">
    <div class="p-6">
        <h1 class="text-2xl font-bold mb-6">Reports</h1>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div class="bg-white rounded-lg shadow p-6">
                <h3 class="font-semibold mb-2">BNM Regulatory Reports</h3>
                <ul class="space-y-2 mt-4">
                    <li><a href="{{ route('reports.msb2') }}" class="text-blue-600 hover:underline">MSB2 Report</a></li>
                    <li><a href="{{ route('reports.lctr') }}" class="text-blue-600 hover:underline">LCTR Report</a></li>
                    <li><a href="{{ route('reports.lmca') }}" class="text-blue-600 hover:underline">LMCA Report</a></li>
                    <li><a href="{{ route('reports.quarterly-lvr') }}" class="text-blue-600 hover:underline">Quarterly LVR</a></li>
                    <li><a href="{{ route('reports.position-limit') }}" class="text-blue-600 hover:underline">Position Limit</a></li>
                </ul>
            </div>

            <div class="bg-white rounded-lg shadow p-6">
                <h3 class="font-semibold mb-2">Analytics</h3>
                <ul class="space-y-2 mt-4">
                    <li><a href="{{ route('reports.monthly-trends') }}" class="text-blue-600 hover:underline">Monthly Trends</a></li>
                    <li><a href="{{ route('reports.profitability') }}" class="text-blue-600 hover:underline">Profitability</a></li>
                    <li><a href="{{ route('reports.customer-analysis') }}" class="text-blue-600 hover:underline">Customer Analysis</a></li>
                    <li><a href="{{ route('reports.compliance-summary') }}" class="text-blue-600 hover:underline">Compliance Summary</a></li>
                </ul>
            </div>

            <div class="bg-white rounded-lg shadow p-6">
                <h3 class="font-semibold mb-2">Report History</h3>
                <ul class="space-y-2 mt-4">
                    <li><a href="{{ route('reports.history') }}" class="text-blue-600 hover:underline">View History</a></li>
                    <li><a href="{{ route('reports.compare') }}" class="text-blue-600 hover:underline">Compare Reports</a></li>
                </ul>
            </div>
        </div>

        @if(isset($recentReports) && $recentReports->count() > 0)
        <div class="bg-white rounded-lg shadow mt-6">
            <div class="px-4 py-3 border-b">
                <h2 class="text-lg font-semibold">Recent Reports</h2>
            </div>
            <table class="w-full">
                <thead class="bg-gray-50">
                    <tr class="text-left text-sm text-gray-500">
                        <th class="px-4 py-2">Report</th>
                        <th class="px-4 py-2">Generated By</th>
                        <th class="px-4 py-2">Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($recentReports as $report)
                    <tr class="border-t">
                        <td class="px-4 py-2">{{ $report->report_type }}</td>
                        <td class="px-4 py-2">{{ $report->generatedBy->name ?? 'N/A' }}</td>
                        <td class="px-4 py-2">{{ $report->generated_at?->format('M d, Y H:i') }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif
    </div>
</x-app-layout>