<x-app-layout title="Reports">
    <div class="space-y-6">
        <x-page-header title="Reports" />

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <x-card title="BNM Regulatory Reports">
                <ul class="space-y-2 mt-4">
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.msb2') }}">MSB2 Report</x-button></li>
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.lmca') }}">LMCA Report</x-button></li>
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.quarterly-lvr') }}">Quarterly LVR</x-button></li>
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.position-limit') }}">Position Limit</x-button></li>
                </ul>
            </x-card>

            <x-card title="Analytics">
                <ul class="space-y-2 mt-4">
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.monthly-trends') }}">Monthly Trends</x-button></li>
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.profitability') }}">Profitability</x-button></li>
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.customer-analysis') }}">Customer Analysis</x-button></li>
                    <li><x-button variant="ghost" size="sm" href="{{ route('reports.compliance-summary') }}">Compliance Summary</x-button></li>
                </ul>
            </x-card>

            <x-card title="Report History" />
        </div>

        @if(isset($recentReports) && $recentReports->count() > 0)
            <x-card title="Recent Reports">
                <x-table>
                    <x-slot:thead>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Report</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Generated By</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Date</th>
                    </x-slot:thead>
                    <x-slot:tbody>
                        @foreach($recentReports as $report)
                            <tr class="hover:bg-canvas-subtle">
                                <td class="px-4 py-3 text-sm">{{ $report->report_type->label() }}</td>
                                <td class="px-4 py-3 text-sm">{{ $report->generatedBy->name ?? 'N/A' }}</td>
                                <td class="px-4 py-3 text-sm">{{ $report->generated_at?->format('M d, Y H:i') }}</td>
                            </tr>
                        @endforeach
                    </x-slot:tbody>
                </x-table>
            </x-card>
        @endif
    </div>
</x-app-layout>
