<?php

namespace App\Services;

use App\Enums\AlertPriority;
use App\Enums\ComplianceFlagType;
use App\Enums\StrStatus;
use App\Events\StrDraftAutoGenerated;
use App\Models\Alert;
use App\Models\Branch;
use App\Models\Customer;
use App\Models\StrReport;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class StrAutomationService
{
    protected array $autoStrTriggers = [
        'structuring' => [
            'enabled' => true,
            'min_transactions' => 3,
            'max_hours' => 1,
            'max_amount' => 3000,
            'priority' => AlertPriority::High,
        ],
        'smurfing' => [
            'enabled' => true,
            'min_related' => 3,
            'priority' => AlertPriority::High,
        ],
        'risk_escalation' => [
            'enabled' => true,
            'min_tier_jump' => 2,
            'priority' => AlertPriority::Medium,
        ],
        'sanction_match' => [
            'enabled' => true,
            'priority' => AlertPriority::Critical,
        ],
    ];

    public function __construct(
        protected NarrativeGenerator $narrativeGenerator,
    ) {}

    public function evaluateAutoStrTriggers(Alert $alert): ?StrReport
    {
        if (! $this->shouldAutoGenerate($alert)) {
            return null;
        }

        $triggers = $this->getApplicableTriggers($alert);

        if (empty($triggers)) {
            return null;
        }

        if ($this->hasRecentStrForPattern($alert)) {
            Log::info('StrAutomationService: Recent STR exists for pattern', [
                'alert_id' => $alert->id,
                'customer_id' => $alert->customer_id,
            ]);
            return null;
        }

        return $this->generateStrDraft($alert, $triggers);
    }

    protected function shouldAutoGenerate(Alert $alert): bool
    {
        if (! config('compliance.str_auto_generate', true)) {
            return false;
        }

        if ($alert->status === StrStatus::Submitted) {
            return false;
        }

        return true;
    }

    protected function getApplicableTriggers(Alert $alert): array
    {
        $triggers = [];

        if ($this->isStructuringAlert($alert)) {
            $triggers[] = [
                'type' => 'Structuring',
                'description' => 'Sub-RM3k transactions detected within 1 hour suggesting structuring',
                'alert_id' => $alert->id,
                'severity' => 'high',
            ];
        }

        if ($this->isSmurfingPattern($alert)) {
            $triggers[] = [
                'type' => 'Smurfing',
                'description' => 'Network pattern detected suggesting smurfing (multiple related parties)',
                'alert_id' => $alert->id,
                'severity' => 'high',
            ];
        }

        if ($this->isRiskEscalation($alert)) {
            $triggers[] = [
                'type' => 'RiskEscalation',
                'description' => 'Customer risk score escalated by 2+ tiers',
                'alert_id' => $alert->id,
                'severity' => 'medium',
            ];
        }

        if ($this->isSanctionMatch($alert)) {
            $triggers[] = [
                'type' => 'SanctionMatch',
                'description' => 'Customer matches sanctions list - immediate review required',
                'alert_id' => $alert->id,
                'severity' => 'critical',
            ];
        }

        return $triggers;
    }

    protected function isStructuringAlert(Alert $alert): bool
    {
        if ($alert->type !== ComplianceFlagType::Structuring) {
            return false;
        }

        return $this->autoStrTriggers['structuring']['enabled'];
    }

    protected function isSmurfingPattern(Alert $alert): bool
    {
        if (! in_array($alert->type, [
            ComplianceFlagType::Structuring,
            ComplianceFlagType::Velocity,
            ComplianceFlagType::UnusualPattern,
        ])) {
            return false;
        }

        if (! $this->autoStrTriggers['smurfing']['enabled']) {
            return false;
        }

        $customer = $alert->customer;
        if (! $customer) {
            return false;
        }

        $relatedCustomers = $this->getRelatedCustomersForSmurfingCheck($customer);

        return count($relatedCustomers) >= $this->autoStrTriggers['smurfing']['min_related'];
    }

    protected function getRelatedCustomersForSmurfingCheck(Customer $customer): array
    {
        if (! method_exists($customer, 'associateRelations')) {
            return [];
        }

        return $customer->associateRelations()
            ->where('relation_type', 'associate')
            ->where('status', 'active')
            ->pluck('related_customer_id')
            ->toArray();
    }

    protected function isRiskEscalation(Alert $alert): bool
    {
        if ($alert->type !== ComplianceFlagType::RiskScoreEscalation) {
            return false;
        }

        if (! $this->autoStrTriggers['risk_escalation']['enabled']) {
            return false;
        }

        return true;
    }

    protected function isSanctionMatch(Alert $alert): bool
    {
        if (! in_array($alert->type, [
            ComplianceFlagType::SanctionMatch,
            ComplianceFlagType::SanctionsHit,
        ])) {
            return false;
        }

        return $this->autoStrTriggers['sanction_match']['enabled'];
    }

    protected function generateStrDraft(Alert $alert, array $triggers): StrReport
    {
        $customer = $alert->customer;
        $branch = $this->getBranchForCustomer($customer);

        $strReport = StrReport::create([
            'str_no' => $this->generateStrNumber(),
            'branch_id' => $branch?->id,
            'customer_id' => $alert->customer_id,
            'alert_id' => $alert->id,
            'transaction_ids' => $this->getTransactionIdsFromAlert($alert),
            'reason' => $this->narrativeGenerator->generateFromAlert($alert),
            'supporting_documents' => [],
            'status' => StrStatus::PendingApproval,
            'suspicion_date' => $alert->created_at,
            'filing_deadline' => $this->calculateFilingDeadline($alert),
            'created_by' => $this->getSystemUserId(),
        ]);

        Log::info('StrAutomationService: Auto-generated STR draft', [
            'str_report_id' => $strReport->id,
            'alert_id' => $alert->id,
            'customer_id' => $alert->customer_id,
            'triggers' => array_column($triggers, 'type'),
        ]);

        event(new StrDraftAutoGenerated($strReport));

        return $strReport;
    }

    protected function generateStrNumber(): string
    {
        $prefix = 'STR';
        $date = now()->format('Ymd');
        $sequence = StrReport::whereDate('created_at', now()->toDateString())->count() + 1;

        return sprintf('%s-%s-%04d', $prefix, $date, $sequence);
    }

    protected function getBranchForCustomer(?Customer $customer): ?Branch
    {
        if (! $customer) {
            return Branch::first();
        }

        return $customer->branch ?? Branch::first();
    }

    protected function getTransactionIdsFromAlert(Alert $alert): array
    {
        if ($alert->flagged_transaction_id) {
            return [$alert->flagged_transaction_id];
        }

        if ($alert->customer_id) {
            $recentTransactions = DB::table('transactions')
                ->where('customer_id', $alert->customer_id)
                ->where('created_at', '>=', now()->subDays(7))
                ->orderBy('created_at', 'desc')
                ->limit(10)
                ->pluck('id')
                ->toArray();

            return $recentTransactions;
        }

        return [];
    }

    protected function calculateFilingDeadline(Alert $alert): \DateTime
    {
        return now()->addDays(3);
    }

    protected function getSystemUserId(): int
    {
        return (int) config('sanctions.system_user_id', 1);
    }

    protected function hasRecentStrForPattern(Alert $alert): bool
    {
        if (! $alert->customer_id) {
            return false;
        }

        $recentStr = StrReport::where('customer_id', $alert->customer_id)
            ->whereIn('status', [
                StrStatus::Draft,
                StrStatus::PendingReview,
                StrStatus::PendingApproval,
                StrStatus::Submitted,
            ])
            ->where('created_at', '>=', now()->subDays(7))
            ->exists();

        return $recentStr;
    }

    public function getAutoStrTriggerConfig(string $trigger): ?array
    {
        return $this->autoStrTriggers[$trigger] ?? null;
    }

    public function isTriggerEnabled(string $trigger): bool
    {
        return $this->autoStrTriggers[$trigger]['enabled'] ?? false;
    }
}
