<?php

namespace App\Http\Controllers\Api\V1\Compliance;

use App\Http\Controllers\Api\V1\Traits\ApiResponse;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V1\Compliance\AuditTrailExportRequest;
use App\Http\Requests\Api\V1\Compliance\AuditTrailRequest;
use App\Services\Compliance\ComplianceReportingService;
use App\Services\Reporting\CsvReportWriter;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * Controller for compliance dashboard API endpoints.
 */
class DashboardController extends Controller
{
    use ApiResponse;

    public function __construct(
        protected ComplianceReportingService $reportingService
    ) {}

    /**
     * Get dashboard KPIs.
     */
    public function kpis(): JsonResponse
    {
        $kpis = $this->reportingService->getDashboardKpis();

        return $this->successResponse($kpis, 'Dashboard KPIs retrieved successfully.', 200, [
            'generated_at' => now()->toIso8601String(),
        ]);
    }

    /**
     * Get BNM regulatory filing calendar.
     */
    public function calendar(): JsonResponse
    {
        $calendar = $this->reportingService->getBnmCalendar();

        return $this->successResponse($calendar, 'Regulatory calendar retrieved successfully.');
    }

    /**
     * Get case aging and SLA metrics.
     */
    public function caseAging(): JsonResponse
    {
        $aging = $this->reportingService->getCaseAging();

        return $this->successResponse($aging, 'Case aging metrics retrieved successfully.');
    }

    /**
     * Get audit trail for compliance actions.
     */
    public function auditTrail(AuditTrailRequest $request): JsonResponse
    {
        $filters = $request->validated();

        $trail = $this->reportingService->getAuditTrail($filters);

        return $this->successResponse($trail['data'], 'Audit trail retrieved successfully.', 200, [
            'pagination' => [
                'current_page' => $trail['current_page'],
                'per_page' => $trail['per_page'],
                'total' => $trail['total'],
                'last_page' => $trail['last_page'],
            ],
        ]);
    }

    /**
     * Export audit trail as CSV.
     */
    public function auditTrailExport(AuditTrailExportRequest $request): BinaryFileResponse
    {
        $filters = $request->validated();

        $export = $this->reportingService->exportAuditTrailToCsv($filters);

        $filename = 'compliance_audit_trail_'.now()->format('Y-m-d_His').'.csv';
        $filepath = app(CsvReportWriter::class)->write($filename, $export['headers'], $export['rows']);

        return response()->download(Storage::path($filepath), $filename, [
            'Content-Type' => 'text/csv',
        ])->deleteFileAfterSend();
    }

    /**
     * Get auto-generated reports.
     */
    public function autoReports(): JsonResponse
    {
        $reports = $this->reportingService->getAutoGeneratedReports();

        return $this->successResponse($reports, 'Auto-generated reports retrieved successfully.');
    }
}
