<?php

namespace App\Http\Controllers\Api\V1\Compliance;

use App\Http\Controllers\Controller;
use App\Services\Compliance\ComplianceReportingService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Controller for compliance dashboard API endpoints.
 */
class DashboardController extends Controller
{
    public function __construct(
        protected ComplianceReportingService $reportingService
    ) {}

    /**
     * Get dashboard KPIs.
     */
    public function kpis(): JsonResponse
    {
        $kpis = $this->reportingService->getDashboardKpis();

        return response()->json([
            'success' => true,
            'data' => $kpis,
            'generated_at' => now()->toIso8601String(),
        ]);
    }

    /**
     * Get BNM regulatory filing calendar.
     */
    public function calendar(): JsonResponse
    {
        $calendar = $this->reportingService->getBnmCalendar();

        return response()->json([
            'success' => true,
            'data' => $calendar,
        ]);
    }

    /**
     * Get case aging and SLA metrics.
     */
    public function caseAging(): JsonResponse
    {
        $aging = $this->reportingService->getCaseAging();

        return response()->json([
            'success' => true,
            'data' => $aging,
        ]);
    }

    /**
     * Get audit trail for compliance actions.
     */
    public function auditTrail(Request $request): JsonResponse
    {
        $filters = $request->validate([
            'per_page' => 'nullable|integer|min:1|max:100',
            'from_date' => 'nullable|date',
            'to_date' => 'nullable|date|after_or_equal:from_date',
            'case_id' => 'nullable|integer',
        ]);

        $trail = $this->reportingService->getAuditTrail($filters);

        return response()->json([
            'success' => true,
            'data' => $trail['data'],
            'pagination' => [
                'current_page' => $trail['current_page'],
                'per_page' => $trail['per_page'],
                'total' => $trail['total'],
                'last_page' => $trail['last_page'],
            ],
        ]);
    }

    /**
     * Export audit trail as CSV.
     */
    public function auditTrailExport(Request $request)
    {
        $filters = $request->validate([
            'from_date' => 'nullable|date',
            'to_date' => 'nullable|date|after_or_equal:from_date',
            'case_id' => 'nullable|integer',
        ]);

        $csv = $this->reportingService->exportAuditTrailToCsv($filters);

        $filename = 'compliance_audit_trail_'.now()->format('Y-m-d_His').'.csv';

        return response()->streamDownload(function () use ($csv) {
            echo $csv;
        }, $filename, [
            'Content-Type' => 'text/csv',
        ]);
    }

    /**
     * Get auto-generated reports.
     */
    public function autoReports(): JsonResponse
    {
        $reports = $this->reportingService->getAutoGeneratedReports();

        return response()->json([
            'success' => true,
            'data' => $reports,
        ]);
    }
}
