<?php

namespace App\Http\Controllers\Api\V1\Compliance;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V1\Compliance\AuditTrailExportRequest;
use App\Http\Requests\Api\V1\Compliance\AuditTrailRequest;
use App\Services\Compliance\ComplianceReportingService;
use Illuminate\Http\JsonResponse;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Controller for compliance dashboard API endpoints.
 */
class DashboardController extends Controller
{
    public function __construct(
        protected ComplianceReportingService $reportingService
    ) {}

    /**
     * Get dashboard KPIs.
     */
    public function kpis(): JsonResponse
    {
        $kpis = $this->reportingService->getDashboardKpis();

        return response()->json([
            'success' => true,
            'data' => $kpis,
            'generated_at' => now()->toIso8601String(),
        ]);
    }

    /**
     * Get BNM regulatory filing calendar.
     */
    public function calendar(): JsonResponse
    {
        $calendar = $this->reportingService->getBnmCalendar();

        return response()->json([
            'success' => true,
            'data' => $calendar,
        ]);
    }

    /**
     * Get case aging and SLA metrics.
     */
    public function caseAging(): JsonResponse
    {
        $aging = $this->reportingService->getCaseAging();

        return response()->json([
            'success' => true,
            'data' => $aging,
        ]);
    }

    /**
     * Get audit trail for compliance actions.
     */
    public function auditTrail(AuditTrailRequest $request): JsonResponse
    {
        $filters = $request->validated();

        $trail = $this->reportingService->getAuditTrail($filters);

        return response()->json([
            'success' => true,
            'data' => $trail['data'],
            'pagination' => [
                'current_page' => $trail['current_page'],
                'per_page' => $trail['per_page'],
                'total' => $trail['total'],
                'last_page' => $trail['last_page'],
            ],
        ]);
    }

    /**
     * Export audit trail as CSV.
     */
    public function auditTrailExport(AuditTrailExportRequest $request): StreamedResponse
    {
        $filters = $request->validated();

        $csv = $this->reportingService->exportAuditTrailToCsv($filters);

        $filename = 'compliance_audit_trail_'.now()->format('Y-m-d_His').'.csv';

        return response()->streamDownload(function () use ($csv) {
            $handle = fopen('php://output', 'w');
            fwrite($handle, $csv);
            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="'.$filename.'"',
        ]);
    }

    /**
     * Get auto-generated reports.
     */
    public function autoReports(): JsonResponse
    {
        $reports = $this->reportingService->getAutoGeneratedReports();

        return response()->json([
            'success' => true,
            'data' => $reports,
        ]);
    }
}
