<div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-200">
        <div class="px-6 py-4 border-b border-gray-200">
            <h2 class="text-lg font-semibold text-gray-900">Compare Report Versions</h2>
        </div>

        <div class="p-6">
            @if($error)
                <div class="mb-4 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
                    {{ $error }}
                </div>
            @endif

            <form wire:submit="compare" class="space-y-4">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Report Type</label>
                        <select wire:model="reportType" class="w-full border-gray-300 rounded-lg border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                            <option value="">Select type...</option>
                            @foreach($reportTypes as $type)
                                <option value="{{ $type }}">{{ $type }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Period Start</label>
                        <input type="date" wire:model="periodStart" class="w-full border-gray-300 rounded-lg border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Version 1</label>
                        <input type="number" wire:model="version1" min="1" placeholder="e.g., 1" class="w-full border-gray-300 rounded-lg border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Version 2</label>
                        <input type="number" wire:model="version2" min="1" placeholder="e.g., 2" class="w-full border-gray-300 rounded-lg border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                    </div>
                </div>

                <div class="flex justify-end">
                    <button type="submit" class="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                        Compare Versions
                    </button>
                </div>
            </form>

            @if($report1 && $report2)
                <div class="mt-8">
                    <h3 class="text-lg font-semibold text-gray-900 mb-4">Comparison Results</h3>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div class="bg-gray-50 rounded-lg p-4">
                            <div class="text-sm text-gray-500">Version {{ $report1->version }}</div>
                            <div class="text-sm text-gray-600 mt-1">Generated: {{ $report1->generated_at->format('d M Y H:i') }}</div>
                            <div class="text-sm text-gray-600">Generated By: {{ $report1->generatedBy->name ?? 'N/A' }}</div>
                            <div class="mt-2 p-2 bg-white rounded border">
                                <pre class="text-xs text-gray-700 whitespace-pre-wrap">{{ $report1->report_data }}</pre>
                            </div>
                        </div>
                        <div class="bg-gray-50 rounded-lg p-4">
                            <div class="text-sm text-gray-500">Version {{ $report2->version }}</div>
                            <div class="text-sm text-gray-600 mt-1">Generated: {{ $report2->generated_at->format('d M Y H:i') }}</div>
                            <div class="text-sm text-gray-600">Generated By: {{ $report2->generatedBy->name ?? 'N/A' }}</div>
                            <div class="mt-2 p-2 bg-white rounded border">
                                <pre class="text-xs text-gray-700 whitespace-pre-wrap">{{ $report2->report_data }}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
