<x-app-layout title="Findings">
    <div class="space-y-6"
         x-data="{
            showDismiss: false,
            showCreateCase: false,
            findingId: null,
            findingRef: null,
            openDismiss(id, ref) { this.findingId = id; this.findingRef = ref; this.showDismiss = true },
            openCreateCase(id, ref) { this.findingId = id; this.findingRef = ref; this.showCreateCase = true }
         }">
        <x-page-header
            title="Compliance Findings"
            description="Findings generated by AML monitoring for review and case escalation"
        />

        @if (session('success'))
            <x-alert type="success">{{ session('success') }}</x-alert>
        @endif

        @if (session('error'))
            <x-alert type="danger">{{ session('error') }}</x-alert>
        @endif

        <x-stat-grid cols="4">
            <x-stat-card label="Total Findings" :value="$stats['total']" />
            <x-stat-card label="New" :value="$stats['new']" color="yellow" />
            <x-stat-card label="Critical Severity" :value="$stats['by_severity']['Critical'] ?? 0" color="red" />
            <x-stat-card label="Dismissed" :value="$stats['by_status']['Dismissed'] ?? 0" color="green" />
        </x-stat-grid>

        <x-filter-bar method="GET">
            <x-select
                name="status"
                :options="[
                    'New' => 'New',
                    'Reviewed' => 'Reviewed',
                    'Case_Created' => 'Case Created',
                    'Dismissed' => 'Dismissed',
                ]"
                placeholder="All Status"
                :selected="request('status')"
                inline
            />
            <x-select
                name="severity"
                :options="['Low' => 'Low', 'Medium' => 'Medium', 'High' => 'High', 'Critical' => 'Critical']"
                placeholder="All Severity"
                :selected="request('severity')"
                inline
            />
            <x-select
                name="type"
                :options="[
                    'Velocity_Exceeded' => 'Velocity Exceeded',
                    'Structuring_Pattern' => 'Structuring Pattern',
                    'Aggregate_Transaction' => 'Aggregate Transaction',
                    'Sanction_Match' => 'Sanction Match',
                    'Location_Anomaly' => 'Location Anomaly',
                    'Currency_Flow_Anomaly' => 'Currency Flow Anomaly',
                    'Counterfeit_Alert' => 'Counterfeit Alert',
                    'Risk_Score_Change' => 'Risk Score Change',
                ]"
                placeholder="All Types"
                :selected="request('type')"
                inline
            />
            <x-input name="date_from" type="date" :value="request('date_from')" inline />
            <x-input name="date_to" type="date" :value="request('date_to')" inline />
            <x-button variant="primary" type="submit">Filter</x-button>
        </x-filter-bar>

        <x-card>
            <div class="overflow-x-auto">
                <x-table>
                    <x-slot:thead>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Reference</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Type</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Severity</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Subject</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Status</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Detected</th>
                        <th class="px-4 py-3 text-left text-xs font-medium text-ink-muted uppercase">Actions</th>
                    </x-slot:thead>
                    <x-slot:tbody>
                        @forelse ($findings as $finding)
                            @php
                                $severityVariant = match ($finding['severity']) {
                                    'Critical' => 'danger',
                                    'High' => 'warning',
                                    'Medium' => 'info',
                                    default => 'success',
                                };
                                $statusVariant = match ($finding['status']) {
                                    'New' => 'warning',
                                    'Reviewed' => 'info',
                                    'Case_Created' => 'purple',
                                    'Dismissed' => 'gray',
                                    default => 'gray',
                                };
                                $typeLabel = \Illuminate\Support\Str::of($finding['finding_type'] ?? '')
                                    ->replace('_', ' ')
                                    ->title();
                                $ref = sprintf('FIN-%06d', $finding['id']);
                            @endphp
                            <tr class="border-t border-border hover:bg-canvas-subtle">
                                <td class="px-4 py-3 text-sm font-medium text-ink">{{ $ref }}</td>
                                <td class="px-4 py-3 text-sm text-ink">{{ $typeLabel }}</td>
                                <td class="px-4 py-3 text-sm">
                                    <x-badge :variant="$severityVariant">{{ $finding['severity'] ?? 'Unknown' }}</x-badge>
                                </td>
                                <td class="px-4 py-3 text-sm text-ink-muted">{{ $finding['subject_label'] ?? 'N/A' }}</td>
                                <td class="px-4 py-3 text-sm">
                                    <x-badge :variant="$statusVariant">
                                        {{ \App\Enums\FindingStatus::tryFrom($finding['status'] ?? '')?->label() ?? ($finding['status'] ?? 'Unknown') }}
                                    </x-badge>
                                </td>
                                <td class="px-4 py-3 text-sm text-ink-muted whitespace-nowrap">
                                    {{ $finding['generated_at']
                                        ? \Illuminate\Support\Carbon::parse($finding['generated_at'])->format('d M Y H:i')
                                        : 'N/A' }}
                                </td>
                                <td class="px-4 py-3 text-sm">
                                    <div class="flex flex-wrap items-center gap-2">
                                        <a href="{{ route('compliance.findings.show', $finding['id']) }}"
                                           class="text-primary hover:underline">View</a>
                                        @if ($finding['can_dismiss'])
                                            <button type="button"
                                                    class="text-danger-text hover:underline"
                                                    @click="openDismiss({{ $finding['id'] }}, '{{ $ref }}')">
                                                Dismiss
                                            </button>
                                        @endif
                                        @if ($finding['can_create_case'])
                                            <button type="button"
                                                    class="text-info hover:underline"
                                                    @click="openCreateCase({{ $finding['id'] }}, '{{ $ref }}')">
                                                Create Case
                                            </button>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <x-empty-state message="No findings match the selected filters." :colspan="7" />
                        @endforelse
                    </x-slot:tbody>
                </x-table>
            </div>
        </x-card>

        @isset($paginator)
            {{ $paginator->links() }}
        @endisset

        {{-- Dismiss modal --}}
        <div x-show="showDismiss" x-cloak @keydown.escape.window="showDismiss = false" class="fixed inset-0 z-50 flex items-center justify-center p-4">
            <div class="absolute inset-0 bg-black/50" @click="showDismiss = false"></div>
            <div x-show="showDismiss"
                 x-transition
                 class="relative bg-surface border border-border rounded-xl shadow-lg w-full max-w-md p-6">
                <h3 class="text-lg font-semibold text-ink mb-1">Dismiss Finding</h3>
                <p class="text-sm text-ink-muted mb-4">
                    Provide a reason for dismissing <span class="font-medium text-ink" x-text="findingRef"></span>.
                </p>
                <form method="POST" :action="'{{ url('compliance/findings') }}/' + findingId + '/dismiss'">
                    @csrf
                    <label for="dismiss-reason" class="block text-sm font-medium text-ink mb-1">Reason <span class="text-danger">*</span></label>
                    <textarea id="dismiss-reason"
                              name="reason"
                              required
                              maxlength="500"
                              rows="3"
                              class="w-full px-3 py-2 text-sm bg-canvas-subtle border border-border rounded-lg focus:bg-surface text-ink focus:outline-none focus:ring-2 focus:ring-primary"
                              placeholder="Explain why this finding is being dismissed..."></textarea>
                    @error('reason')
                        <p class="mt-1 text-xs text-danger-text">{{ $message }}</p>
                    @enderror
                    <div class="mt-4 flex justify-end gap-3">
                        <x-button variant="secondary" type="button" @click="showDismiss = false">Cancel</x-button>
                        <x-button variant="danger" type="submit">Dismiss Finding</x-button>
                    </div>
                </form>
            </div>
        </div>

        {{-- Create Case modal --}}
        <div x-show="showCreateCase" x-cloak @keydown.escape.window="showCreateCase = false" class="fixed inset-0 z-50 flex items-center justify-center p-4">
            <div class="absolute inset-0 bg-black/50" @click="showCreateCase = false"></div>
            <div x-show="showCreateCase"
                 x-transition
                 class="relative bg-surface border border-border rounded-xl shadow-lg w-full max-w-md p-6">
                <h3 class="text-lg font-semibold text-ink mb-1">Create Case from Finding</h3>
                <p class="text-sm text-ink-muted mb-4">
                    Escalate <span class="font-medium text-ink" x-text="findingRef"></span> into a compliance case.
                    The case will be assigned to you.
                </p>
                <form method="POST" :action="'{{ url('compliance/findings') }}/' + findingId + '/create-case'">
                    @csrf
                    <label for="case-type" class="block text-sm font-medium text-ink mb-1">Case Type <span class="text-danger">*</span></label>
                    <select id="case-type" name="case_type" required
                            class="w-full px-3 py-2 text-sm bg-canvas-subtle border border-border rounded-lg focus:bg-surface text-ink focus:outline-none focus:ring-2 focus:ring-primary">
                        @foreach (\App\Enums\ComplianceCaseType::cases() as $caseType)
                            <option value="{{ $caseType->value }}">{{ $caseType->label() }}</option>
                        @endforeach
                    </select>
                    <label for="case-summary" class="block text-sm font-medium text-ink mt-4 mb-1">Summary</label>
                    <textarea id="case-summary"
                              name="summary"
                              rows="3"
                              maxlength="1000"
                              class="w-full px-3 py-2 text-sm bg-canvas-subtle border border-border rounded-lg focus:bg-surface text-ink focus:outline-none focus:ring-2 focus:ring-primary"
                              placeholder="Optional case summary..."></textarea>
                    <div class="mt-4 flex justify-end gap-3">
                        <x-button variant="secondary" type="button" @click="showCreateCase = false">Cancel</x-button>
                        <x-button variant="primary" type="submit">Create Case</x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>
