@extends('layouts.base')

@section('title', 'Report History')

@section('content')
<div>
    <div class="bg-white rounded-xl shadow-sm border border-gray-200">
        <div class="px-6 py-4 border-b border-gray-200">
            <div class="flex items-center justify-between">
                <h2 class="text-lg font-semibold text-gray-900">Report History</h2>
                <div class="flex items-center gap-4">
                    <select wire:model.live="reportType" class="text-sm border-gray-300 rounded-lg border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                        <option value="">All Types</option>
                        @foreach($reportTypes as $type)
                            <option value="{{ $type }}">{{ $type }}</option>
                        @endforeach
                    </select>
                    <input type="date" wire:model.live="periodStart" class="text-sm border-gray-300 rounded-lg border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                </div>
            </div>
        </div>

        <div class="p-6">
            @if($reports->isEmpty())
                <div class="text-center py-8 text-gray-500">
                    No reports found.
                </div>
            @else
                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report Type</th>
                                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Period</th>
                                <th class="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Version</th>
                                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Submitted By</th>
                                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated At</th>
                                <th class="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                            @foreach($reports as $report)
                                <tr class="hover:bg-gray-50">
                                    <td class="px-4 py-3 text-sm font-medium text-gray-900">{{ $report->report_type }}</td>
                                    <td class="px-4 py-3 text-sm text-gray-600">{{ $report->period_start ? \Carbon\Carbon::parse($report->period_start)->format('d M Y') : 'N/A' }}</td>
                                    <td class="px-4 py-3 text-sm text-gray-600 text-center">{{ $report->version }}</td>
                                    <td class="px-4 py-3 text-sm text-gray-600">{{ $report->generatedBy->name ?? 'N/A' }}</td>
                                    <td class="px-4 py-3 text-sm text-gray-600">{{ $report->submittedBy->name ?? 'Pending' }}</td>
                                    <td class="px-4 py-3 text-sm text-gray-500">{{ $report->generated_at->format('d M Y H:i') }}</td>
                                    <td class="px-4 py-3 text-center">
                                        <a href="{{ route('reports.download', basename($report->file_path)) }}" class="text-indigo-600 hover:text-indigo-900 text-sm font-medium">
                                            Download
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <div class="mt-4">
                    <div class="flex justify-center">
                        <nav class="relative z-0 inline-flex -space-x-px rounded-md shadow-sm">
                            @if($reports->onFirstPage())
                                <span class="relative inline-flex items-center px-3 py-2 text-sm font-medium text-gray-400 border border-gray-300 rounded-l-md">Previous</span>
                            @else
                                <button wire:click="previousPage" class="relative inline-flex items-center px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-l-md hover:bg-gray-50">Previous</button>
                            @endif

                            @foreach($reports->getUrlRange(1, $reports->lastPage()) as $page => $url)
                                @if($page == $reports->currentPage())
                                    <span class="relative inline-flex items-center px-3 py-2 text-sm font-medium text-white bg-indigo-600 border border-indigo-600">{{ $page }}</span>
                                @else
                                    <button wire:click="gotoPage({{ $page }})" class="relative inline-flex items-center px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 hover:bg-gray-50">{{ $page }}</button>
                                @endif
                            @endforeach

                            @if($reports->hasMorePages())
                                <button wire:click="nextPage" class="relative inline-flex items-center px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-r-md hover:bg-gray-50">Next</button>
                            @else
                                <span class="relative inline-flex items-center px-3 py-2 text-sm font-medium text-gray-400 border border-gray-300 rounded-r-md">Next</span>
                            @endif
                        </nav>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection
