@extends('layouts.app')

@section('title', 'Compare Reports - CEMS-MY')

@section('content')
<nav class="breadcrumb">
    <a href="{{ route('reports.index') }}">Reports</a>
    <span>›</span>
    <a href="{{ route('reports.history') }}">History</a>
    <span>›</span>
    <span>Compare</span>
</nav>

<div class="page-header">
    <h1>Compare Report Versions</h1>
    <p>{{ $report1->report_type }} - {{ $report1->period_start->format('Y-m-d') }}</p>
</div>

<div class="compare-container">
    <div class="compare-column">
        <div class="compare-header">
            <h2>Version {{ $report1->version }}</h2>
            <span class="timestamp">Generated {{ $report1->generated_at->format('Y-m-d H:i:s') }}</span>
            <span class="generator">By {{ $report1->generatedBy->name ?? 'System' }}</span>
        </div>
        <div class="compare-body">
            <table class="compare-table">
                <tr>
                    <th>Report Type:</th>
                    <td>{{ $report1->report_type }}</td>
                </tr>
                <tr>
                    <th>Period:</th>
                    <td>{{ $report1->period_start->format('Y-m-d') }} to {{ $report1->period_end->format('Y-m-d') }}</td>
                </tr>
                <tr>
                    <th>Generated At:</th>
                    <td>{{ $report1->generated_at->format('Y-m-d H:i') }}</td>
                </tr>
                <tr>
                    <th>Generated By:</th>
                    <td>{{ $report1->generatedBy->name ?? 'System' }}</td>
                </tr>
                <tr>
                    <th>File Format:</th>
                    <td>{{ $report1->file_format }}</td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td>
                        <span class="status-badge status-{{ strtolower($report1->status) }}">
                            {{ $report1->status }}
                        </span>
                    </td>
                </tr>
                @if($report1->submitted_at)
                <tr>
                    <th>Submitted At:</th>
                    <td>{{ $report1->submitted_at->format('Y-m-d H:i') }}</td>
                </tr>
                @endif
                @if($report1->notes)
                <tr>
                    <th>Notes:</th>
                    <td>{{ $report1->notes }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>

    <div class="compare-column">
        <div class="compare-header">
            <h2>Version {{ $report2->version }}</h2>
            <span class="timestamp">Generated {{ $report2->generated_at->format('Y-m-d H:i:s') }}</span>
            <span class="generator">By {{ $report2->generatedBy->name ?? 'System' }}</span>
        </div>
        <div class="compare-body">
            <table class="compare-table">
                <tr>
                    <th>Report Type:</th>
                    <td>{{ $report2->report_type }}</td>
                </tr>
                <tr>
                    <th>Period:</th>
                    <td>{{ $report2->period_start->format('Y-m-d') }} to {{ $report2->period_end->format('Y-m-d') }}</td>
                </tr>
                <tr>
                    <th>Generated At:</th>
                    <td>{{ $report2->generated_at->format('Y-m-d H:i') }}</td>
                </tr>
                <tr>
                    <th>Generated By:</th>
                    <td>{{ $report2->generatedBy->name ?? 'System' }}</td>
                </tr>
                <tr>
                    <th>File Format:</th>
                    <td>{{ $report2->file_format }}</td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td>
                        <span class="status-badge status-{{ strtolower($report2->status) }}">
                            {{ $report2->status }}
                        </span>
                    </td>
                </tr>
                @if($report2->submitted_at)
                <tr>
                    <th>Submitted At:</th>
                    <td>{{ $report2->submitted_at->format('Y-m-d H:i') }}</td>
                </tr>
                @endif
                @if($report2->notes)
                <tr>
                    <th>Notes:</th>
                    <td>{{ $report2->notes }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>
</div>

<div class="button-group" style="margin-top: 1.5rem;">
    <a href="{{ route('reports.history') }}" class="btn btn-secondary">Back to History</a>
</div>

<style>
.compare-container {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
}

@media (max-width: 768px) {
    .compare-container {
        grid-template-columns: 1fr;
    }
}

.compare-column {
    background: white;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    overflow: hidden;
}

.compare-header {
    background: #f7fafc;
    padding: 1rem 1.5rem;
    border-bottom: 1px solid #e2e8f0;
}

.compare-header h2 {
    font-size: 1.125rem;
    color: #2d3748;
    margin: 0 0 0.5rem 0;
}

.compare-header .timestamp,
.compare-header .generator {
    display: block;
    font-size: 0.875rem;
    color: #718096;
}

.compare-body {
    padding: 1.5rem;
}

.compare-table {
    width: 100%;
    border-collapse: collapse;
}

.compare-table th,
.compare-table td {
    padding: 0.75rem;
    text-align: left;
    border-bottom: 1px solid #e2e8f0;
}

.compare-table th {
    color: #4a5568;
    font-weight: 500;
    width: 40%;
}

.compare-table td {
    color: #2d3748;
}

.compare-table tr:last-child th,
.compare-table tr:last-child td {
    border-bottom: none;
}

.status-submitted {
    background: #c6f6d5;
    color: #276749;
}

.status-generated {
    background: #bee3f8;
    color: #2c5282;
}

.status-archived {
    background: #e2e8f0;
    color: #4a5568;
}
</style>
@endsection