@extends('layouts.app')

@section('title', 'Compare Reports - CEMS-MY')

@section('content')
<nav class="flex items-center gap-2 mb-4 text-sm text-gray-500">
    <a href="{{ route('reports.index') }}" class="text-blue-600 no-underline hover:underline">Reports</a>
    <span>›</span>
    <a href="{{ route('reports.history') }}" class="text-blue-600 no-underline hover:underline">History</a>
    <span>›</span>
    <span>Compare</span>
</nav>

<div class="mb-6">
    <h1 class="text-2xl font-bold text-blue-900 mb-1">Compare Report Versions</h1>
    <p class="text-gray-500 text-sm">{{ $report1->report_type }} - {{ $report1->period_start->format('Y-m-d') }}</p>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
    <div class="bg-white rounded-lg shadow-sm overflow-hidden">
        <div class="bg-gray-50 px-6 py-4 border-b border-gray-200">
            <h2 class="text-lg font-semibold text-gray-800 mb-1">Version {{ $report1->version }}</h2>
            <span class="block text-sm text-gray-500">Generated {{ $report1->generated_at->format('Y-m-d H:i:s') }}</span>
            <span class="block text-sm text-gray-500">By {{ $report1->generatedBy->name ?? 'System' }}</span>
        </div>
        <div class="p-6">
            <table class="w-full border-collapse">
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium w-2/5">Report Type:</th>
                    <td class="py-3 text-gray-800">{{ $report1->report_type }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Period:</th>
                    <td class="py-3 text-gray-800">{{ $report1->period_start->format('Y-m-d') }} to {{ $report1->period_end->format('Y-m-d') }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Generated At:</th>
                    <td class="py-3 text-gray-800">{{ $report1->generated_at->format('Y-m-d H:i') }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Generated By:</th>
                    <td class="py-3 text-gray-800">{{ $report1->generatedBy->name ?? 'System' }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">File Format:</th>
                    <td class="py-3 text-gray-800">{{ $report1->file_format }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Status:</th>
                    <td class="py-3">
                        <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold {{ strtolower($report1->status) === 'submitted' ? 'bg-green-100 text-green-800' : (strtolower($report1->status) === 'archived' ? 'bg-gray-200 text-gray-600' : 'bg-blue-100 text-blue-800') }}">
                            {{ $report1->status }}
                        </span>
                    </td>
                </tr>
                @if($report1->submitted_at)
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Submitted At:</th>
                    <td class="py-3 text-gray-800">{{ $report1->submitted_at->format('Y-m-d H:i') }}</td>
                </tr>
                @endif
                @if($report1->notes)
                <tr>
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Notes:</th>
                    <td class="py-3 text-gray-800">{{ $report1->notes }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>

    <div class="bg-white rounded-lg shadow-sm overflow-hidden">
        <div class="bg-gray-50 px-6 py-4 border-b border-gray-200">
            <h2 class="text-lg font-semibold text-gray-800 mb-1">Version {{ $report2->version }}</h2>
            <span class="block text-sm text-gray-500">Generated {{ $report2->generated_at->format('Y-m-d H:i:s') }}</span>
            <span class="block text-sm text-gray-500">By {{ $report2->generatedBy->name ?? 'System' }}</span>
        </div>
        <div class="p-6">
            <table class="w-full border-collapse">
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium w-2/5">Report Type:</th>
                    <td class="py-3 text-gray-800">{{ $report2->report_type }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Period:</th>
                    <td class="py-3 text-gray-800">{{ $report2->period_start->format('Y-m-d') }} to {{ $report2->period_end->format('Y-m-d') }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Generated At:</th>
                    <td class="py-3 text-gray-800">{{ $report2->generated_at->format('Y-m-d H:i') }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Generated By:</th>
                    <td class="py-3 text-gray-800">{{ $report2->generatedBy->name ?? 'System' }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">File Format:</th>
                    <td class="py-3 text-gray-800">{{ $report2->file_format }}</td>
                </tr>
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Status:</th>
                    <td class="py-3">
                        <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold {{ strtolower($report2->status) === 'submitted' ? 'bg-green-100 text-green-800' : (strtolower($report2->status) === 'archived' ? 'bg-gray-200 text-gray-600' : 'bg-blue-100 text-blue-800') }}">
                            {{ $report2->status }}
                        </span>
                    </td>
                </tr>
                @if($report2->submitted_at)
                <tr class="border-b border-gray-100">
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Submitted At:</th>
                    <td class="py-3 text-gray-800">{{ $report2->submitted_at->format('Y-m-d H:i') }}</td>
                </tr>
                @endif
                @if($report2->notes)
                <tr>
                    <th class="py-3 pr-4 text-left text-gray-600 font-medium">Notes:</th>
                    <td class="py-3 text-gray-800">{{ $report2->notes }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>
</div>

<div class="flex gap-4 mt-6">
    <a href="{{ route('reports.history') }}" class="px-6 py-3 bg-gray-200 text-gray-700 no-underline rounded font-semibold hover:bg-gray-300 transition-colors">Back to History</a>
</div>
@endsection
