@extends('layouts.app')

@section('title', 'Compare Reports - CEMS-MY')

@section('content')
<div class="page-header">
    <div class="page-header__content">
        <h1 class="page-header__title">Compare Report Versions</h1>
        <p class="page-header__subtitle">{{ $report1->report_type }} - {{ $report1->period_start->format('Y-m-d') }}</p>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
    <!-- Version 1 Card -->
    <div class="card">
        <div class="card-header">
            <h3 class="text-lg font-semibold text-gray-800">Version {{ $report1->version }}</h3>
            <p class="text-sm text-gray-500 mt-1">Generated {{ $report1->generated_at->format('Y-m-d H:i:s') }} by {{ $report1->generatedBy->name ?? 'System' }}</p>
        </div>
        <div class="card-body">
            <table class="w-full">
                <tr>
                    <th class="text-left text-gray-600 py-2">Report Type:</th>
                    <td class="py-2">{{ $report1->report_type }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Period:</th>
                    <td class="py-2">{{ $report1->period_start->format('Y-m-d') }} to {{ $report1->period_end->format('Y-m-d') }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Generated At:</th>
                    <td class="py-2">{{ $report1->generated_at->format('Y-m-d H:i') }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Generated By:</th>
                    <td class="py-2">{{ $report1->generatedBy->name ?? 'System' }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">File Format:</th>
                    <td class="py-2">{{ $report1->file_format }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Status:</th>
                    <td class="py-2">
                        <span class="status-badge status-badge--{{ strtolower($report1->status) }}">
                            {{ $report1->status }}
                        </span>
                    </td>
                </tr>
                @if($report1->submitted_at)
                <tr>
                    <th class="text-left text-gray-600 py-2">Submitted At:</th>
                    <td class="py-2">{{ $report1->submitted_at->format('Y-m-d H:i') }}</td>
                </tr>
                @endif
                @if($report1->notes)
                <tr>
                    <th class="text-left text-gray-600 py-2">Notes:</th>
                    <td class="py-2">{{ $report1->notes }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>

    <!-- Version 2 Card -->
    <div class="card">
        <div class="card-header">
            <h3 class="text-lg font-semibold text-gray-800">Version {{ $report2->version }}</h3>
            <p class="text-sm text-gray-500 mt-1">Generated {{ $report2->generated_at->format('Y-m-d H:i:s') }} by {{ $report2->generatedBy->name ?? 'System' }}</p>
        </div>
        <div class="card-body">
            <table class="w-full">
                <tr>
                    <th class="text-left text-gray-600 py-2">Report Type:</th>
                    <td class="py-2">{{ $report2->report_type }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Period:</th>
                    <td class="py-2">{{ $report2->period_start->format('Y-m-d') }} to {{ $report2->period_end->format('Y-m-d') }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Generated At:</th>
                    <td class="py-2">{{ $report2->generated_at->format('Y-m-d H:i') }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Generated By:</th>
                    <td class="py-2">{{ $report2->generatedBy->name ?? 'System' }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">File Format:</th>
                    <td class="py-2">{{ $report2->file_format }}</td>
                </tr>
                <tr>
                    <th class="text-left text-gray-600 py-2">Status:</th>
                    <td class="py-2">
                        <span class="status-badge status-badge--{{ strtolower($report2->status) }}">
                            {{ $report2->status }}
                        </span>
                    </td>
                </tr>
                @if($report2->submitted_at)
                <tr>
                    <th class="text-left text-gray-600 py-2">Submitted At:</th>
                    <td class="py-2">{{ $report2->submitted_at->format('Y-m-d H:i') }}</td>
                </tr>
                @endif
                @if($report2->notes)
                <tr>
                    <th class="text-left text-gray-600 py-2">Notes:</th>
                    <td class="py-2">{{ $report2->notes }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>
</div>

<div class="flex gap-4">
    <a href="{{ route('reports.history') }}" class="btn btn--secondary">Back to History</a>
</div>
@endsection
