@extends('layouts.app')

@section('title', 'Report History - CEMS-MY')

@section('content')
<nav class="breadcrumb">
    <a href="{{ route('reports.index') }}">Reports</a>
    <span>›</span>
    <span>History</span>
</nav>

<div class="page-header">
    <h1>Report History</h1>
    <p>View all generated reports with version tracking</p>
</div>

<div class="control-card">
    <form method="GET" action="{{ route('reports.history') }}" class="control-row">
        <div class="form-group">
            <label for="type">Report Type</label>
            <select id="type" name="type" class="form-control">
                <option value="">All Types</option>
                @foreach($reportTypes as $type)
                    <option value="{{ $type }}" {{ $type === $reportType ? 'selected' : '' }}>{{ $type }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="period">Period Start</label>
            <input type="month" id="period" name="period" value="{{ $periodStart }}" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary">Filter</button>
        <a href="{{ route('reports.history') }}" class="btn btn-secondary">Clear</a>
    </form>
</div>

<div class="table-card">
    <table class="data-table">
        <thead>
            <tr>
                <th>Report Type</th>
                <th>Period</th>
                <th>Version</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reports as $report)
            <tr>
                <td><strong>{{ $report->report_type }}</strong></td>
                <td>{{ $report->period_start->format('Y-m-d') }} to {{ $report->period_end->format('Y-m-d') }}</td>
                <td>
                    <span class="version-badge">v{{ $report->version }}</span>
                    @if($report->isLatestVersion())
                        <span class="status-badge status-generated">Latest</span>
                    @endif
                </td>
                <td>{{ $report->generatedBy->name ?? 'System' }}</td>
                <td>{{ $report->generated_at->format('Y-m-d H:i') }}</td>
                <td>
                    <span class="status-badge status-{{ strtolower($report->status) }}">
                        {{ $report->status }}
                    </span>
                </td>
                <td>
                    <div style="display: flex; gap: 0.5rem;">
                        @if($report->file_path)
                            <a href="{{ route('reports.download', basename($report->file_path)) }}" class="btn btn-sm btn-success">Download</a>
                        @endif
                        @if($report->submitted_at)
                            <span style="color: #718096; font-size: 0.75rem;">
                                Submitted {{ $report->submitted_at->format('Y-m-d') }}
                            </span>
                        @endif
                    </div>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 2rem; color: #718096;">
                    No reports found.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    @if($reports->hasPages())
    <div style="margin-top: 1rem;">
        {{ $reports->links() }}
    </div>
    @endif
</div>
@endsection