@extends('layouts.app')

@section('title', 'Report History - CEMS-MY')

@section('breadcrumbs')
<nav class="breadcrumbs" aria-label="Breadcrumb">
    <ol class="breadcrumbs__list">
        <li class="breadcrumbs__item">
            <a href="{{ route('dashboard') }}" class="breadcrumbs__link">Dashboard</a>
            <svg class="breadcrumbs__separator" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>
        </li>
        <li class="breadcrumbs__item">
            <a href="{{ route('reports.index') }}" class="breadcrumbs__link">Reports</a>
            <svg class="breadcrumbs__separator" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>
        </li>
        <li class="breadcrumbs__item breadcrumbs__item--current" aria-current="page">
            <span class="breadcrumbs__text">History</span>
        </li>
    </ol>
</nav>
@endsection

@section('content')
<div class="page-header">
    <div class="page-header__content">
        <h1 class="page-header__title">Report History</h1>
        <p class="page-header__subtitle">View all generated reports with version tracking</p>
    </div>
</div>

<div class="card mb-6">
    <div class="card-header">
        <h3 class="text-lg font-semibold text-gray-800">Filter Reports</h3>
    </div>
    <div class="card-body">
        <form method="GET" action="{{ route('reports.history') }}" class="flex items-end gap-4">
            <div>
                <label for="type" class="form-label">Report Type</label>
                <select id="type" name="type" class="form-select">
                    <option value="">All Types</option>
                    @foreach($reportTypes as $type)
                        <option value="{{ $type }}" {{ $type === $reportType ? 'selected' : '' }}>{{ $type }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label for="period" class="form-label">Period Start</label>
                <input type="month" id="period" name="period" value="{{ $periodStart }}" class="form-input">
            </div>
            <button type="submit" class="btn btn--primary">Filter</button>
            <a href="{{ route('reports.history') }}" class="btn btn--secondary">Clear</a>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-body p-0">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Report Type</th>
                    <th>Period</th>
                    <th>Version</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                <tr>
                    <td><strong>{{ $report->report_type }}</strong></td>
                    <td>{{ $report->period_start->format('Y-m-d') }} to {{ $report->period_end->format('Y-m-d') }}</td>
                    <td>
                        <span class="version-badge">v{{ $report->version }}</span>
                        @if($report->isLatestVersion())
                            <span class="status-badge status-badge--active">Latest</span>
                        @endif
                    </td>
                    <td>{{ $report->generatedBy->name ?? 'System' }}</td>
                    <td>{{ $report->generated_at->format('Y-m-d H:i') }}</td>
                    <td>
                        <span class="status-badge status-badge--{{ strtolower($report->status) }}">
                            {{ $report->status }}
                        </span>
                    </td>
                    <td>
                        @if($report->file_path)
                            <a href="{{ route('reports.download', basename($report->file_path)) }}" class="btn btn--success btn--sm">Download</a>
                        @endif
                        @if($report->submitted_at)
                            <span class="text-gray-500 text-sm ml-2">
                                Submitted {{ $report->submitted_at->format('Y-m-d') }}
                            </span>
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="text-center py-8 text-gray-500">
                        No reports found.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    @if($reports->hasPages())
    <div class="p-4 border-t border-gray-200">
        {{ $reports->links() }}
    </div>
    @endif
</div>
@endsection