<?php

namespace App\Http\Controllers\Api\Compliance;

use App\Http\Controllers\Controller;
use App\Services\Compliance\ComplianceReportingService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Controller for compliance dashboard API endpoints.
 * Provides KPIs, calendar, case aging, audit trail, and auto-generated reports.
 */
class DashboardController extends Controller
{
    protected ComplianceReportingService $reportingService;

    public function __construct(ComplianceReportingService $reportingService)
    {
        $this->reportingService = $reportingService;
    }

    /**
     * Get dashboard KPIs.
     *
     * Returns case summary, STR status, EDD status, open findings (last 7 days),
     * and risk distribution across customer portfolio.
     */
    public function kpis(): JsonResponse
    {
        $kpis = $this->reportingService->getDashboardKpis();

        return response()->json([
            'success' => true,
            'data' => $kpis,
            'generated_at' => now()->toIso8601String(),
        ]);
    }

    /**
     * Get BNM regulatory filing calendar.
     *
     * Returns upcoming filing deadlines for LCTR (monthly), LMCA (monthly),
     * QLVR (quarterly), and STR (rolling 3-day deadline).
     */
    public function calendar(): JsonResponse
    {
        $calendar = $this->reportingService->getBnmCalendar();

        return response()->json([
            'success' => true,
            'data' => $calendar,
        ]);
    }

    /**
     * Get case aging and SLA metrics.
     *
     * Returns average time to first response, average resolution time by severity,
     * cases breaching SLA, and oldest open case.
     */
    public function caseAging(): JsonResponse
    {
        $aging = $this->reportingService->getCaseAging();

        return response()->json([
            'success' => true,
            'data' => $aging,
        ]);
    }

    /**
     * Get audit trail for compliance actions.
     *
     * Returns paginated/filterable list of compliance actions including
     * case ID, type, status, opened/closed dates, assigned officer,
     * resolution, linked STR, and action counts.
     */
    public function auditTrail(Request $request): JsonResponse
    {
        $filters = $request->validate([
            'per_page' => 'nullable|integer|min:1|max:100',
            'from_date' => 'nullable|date',
            'to_date' => 'nullable|date|after_or_equal:from_date',
            'case_id' => 'nullable|integer',
        ]);

        $trail = $this->reportingService->getAuditTrail($filters);

        return response()->json([
            'success' => true,
            'data' => $trail['data'],
            'pagination' => [
                'current_page' => $trail['current_page'],
                'per_page' => $trail['per_page'],
                'total' => $trail['total'],
                'last_page' => $trail['last_page'],
            ],
        ]);
    }

    /**
     * Export audit trail as CSV.
     *
     * @return \Symfony\Component\HttpFoundation\StreamedResponse
     */
    public function auditTrailExport(Request $request)
    {
        $filters = $request->validate([
            'from_date' => 'nullable|date',
            'to_date' => 'nullable|date|after_or_equal:from_date',
            'case_id' => 'nullable|integer',
        ]);

        $csv = $this->reportingService->exportAuditTrailToCsv($filters);

        $filename = 'compliance_audit_trail_'.now()->format('Y-m-d_His').'.csv';

        return response()->streamDownload(function () use ($csv) {
            echo $csv;
        }, $filename, [
            'Content-Type' => 'text/csv',
        ]);
    }

    /**
     * Get auto-generated reports.
     *
     * Returns list of auto-generated reports (MSB2, LCTR, LMCA, QLVR)
     * that are pending approval before BNM submission.
     */
    public function autoReports(): JsonResponse
    {
        $reports = $this->reportingService->getAutoGeneratedReports();

        return response()->json([
            'success' => true,
            'data' => $reports,
        ]);
    }
}
