<div class="min-h-screen bg-[var(--color-background)] p-6">
    <div class="max-w-7xl mx-auto">
        <h1 class="text-2xl font-bold text-[var(--color-ink)] mb-6">Report History</h1>

        <div class="bg-white rounded-lg shadow overflow-hidden">
            <table class="w-full">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-4 py-3 text-left text-sm font-medium text-[var(--color-ink)]">Report Number</th>
                        <th class="px-4 py-3 text-left text-sm font-medium text-[var(--color-ink)]">Type</th>
                        <th class="px-4 py-3 text-left text-sm font-medium text-[var(--color-ink)]">Period</th>
                        <th class="px-4 py-3 text-right text-sm font-medium text-[var(--color-ink)]">Amount</th>
                        <th class="px-4 py-3 text-left text-sm font-medium text-[var(--color-ink)]">Generated By</th>
                        <th class="px-4 py-3 text-left text-sm font-medium text-[var(--color-ink)]">Date</th>
                        <th class="px-4 py-3 text-left text-sm font-medium text-[var(--color-ink)]">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($reports as $report)
                    <tr class="border-t border-[var(--color-border)]">
                        <td class="px-4 py-3">{{ $report->report_number }}</td>
                        <td class="px-4 py-3">{{ strtoupper($report->type) }}</td>
                        <td class="px-4 py-3">{{ $report->period }}</td>
                        <td class="px-4 py-3 text-right">${{ number_format($report->amount, 2) }}</td>
                        <td class="px-4 py-3">{{ $report->user->name }}</td>
                        <td class="px-4 py-3 text-sm text-gray-500">{{ $report->created_at->format('Y-m-d') }}</td>
                        <td class="px-4 py-3">
                            <a href="{{ route('reports.show', $report->id) }}" class="text-blue-600 hover:underline">View</a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="px-4 py-3 text-center">No history found</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <div class="mt-4">
            {{ $reports->links() }}
        </div>
    </div>
</div>