<?php

namespace App\Enums;

use App\Helpers\Thresholdable;

/**
 * Compliance Flag Type Enum
 *
 * Represents the different types of compliance flags that can be
 * raised for a transaction requiring review.
 */
enum ComplianceFlagType: string
{
    use Thresholdable;
    case LargeAmount = 'Large_Amount';
    case SanctionsHit = 'Sanctions_Hit';
    case Velocity = 'Velocity';
    case Structuring = 'Structuring';
    case EddRequired = 'EDD_Required';
    case PepStatus = 'PEP_Status';
    case SanctionMatch = 'Sanction_Match';
    case HighRiskCustomer = 'High_Risk_Customer';
    case UnusualPattern = 'Unusual_Pattern';
    case ManualReview = 'Manual_Review';
    case HighRiskCountry = 'High_Risk_Country';
    case RoundAmount = 'Round_Amount';
    case ProfileDeviation = 'Profile_Deviation';
    case AmlRuleTriggered = 'Aml_Rule_Triggered';
    case CounterfeitCurrency = 'Counterfeit_Currency';
    case RiskScoreEscalation = 'Risk_Score_Escalation';

    /**
     * Check if this flag type indicates a sanctions issue.
     */
    public function isSanctionsRelated(): bool
    {
        return in_array($this, [self::SanctionsHit, self::SanctionMatch], true);
    }

    /**
     * Check if this flag type indicates a velocity issue.
     */
    public function isVelocityRelated(): bool
    {
        return $this === self::Velocity;
    }

    /**
     * Check if this flag type indicates structuring.
     */
    public function isStructuring(): bool
    {
        return $this === self::Structuring;
    }

    /**
     * Check if this flag type requires EDD.
     */
    public function requiresEdd(): bool
    {
        return in_array($this, [self::EddRequired, self::LargeAmount, self::HighRiskCustomer], true);
    }

    /**
     * Check if this is a high-priority flag requiring immediate attention.
     */
    public function isHighPriority(): bool
    {
        return in_array($this, [
            self::SanctionsHit,
            self::SanctionMatch,
            self::Structuring,
        ], true);
    }

    /**
     * Check if this flag type is automatically generated by the system.
     */
    public function isAutoGenerated(): bool
    {
        return $this !== self::ManualReview;
    }

    /**
     * Get the threshold amount associated with this flag type, if any.
     */
    public function thresholdAmount(): ?string
    {
        return match ($this) {
            self::LargeAmount => self::getLargeTransactionThreshold(),
            self::EddRequired => self::getLargeTransactionThreshold(),
            self::Velocity => self::getVelocityAlertThreshold(),
            default => null,
        };
    }

    /**
     * Get a human-readable label for the flag type.
     */
    public function label(): string
    {
        return match ($this) {
            self::LargeAmount => 'Large Amount',
            self::SanctionsHit => 'Sanctions Hit',
            self::Velocity => 'Velocity Check',
            self::Structuring => 'Structuring Detection',
            self::EddRequired => 'EDD Required',
            self::PepStatus => 'PEP Status',
            self::SanctionMatch => 'Sanction Match',
            self::HighRiskCustomer => 'High Risk Customer',
            self::UnusualPattern => 'Unusual Pattern',
            self::ManualReview => 'Manual Review',
            self::HighRiskCountry => 'High Risk Country',
            self::RoundAmount => 'Round Amount',
            self::ProfileDeviation => 'Profile Deviation',
            self::AmlRuleTriggered => 'AML Rule Triggered',
            self::CounterfeitCurrency => 'Counterfeit Currency',
            self::RiskScoreEscalation => 'Risk Score Escalation',
        };
    }

    /**
     * Get a description of what this flag means.
     */
    public function description(): string
    {
        return match ($this) {
            self::LargeAmount => 'Transaction amount exceeds threshold',
            self::SanctionsHit => 'Potential match with sanctions list',
            self::Velocity => '24-hour velocity threshold exceeded',
            self::Structuring => 'Potential structuring behavior detected',
            self::EddRequired => 'Enhanced Due Diligence required',
            self::PepStatus => 'Customer is a Politically Exposed Person',
            self::SanctionMatch => 'Customer matches sanctions database',
            self::HighRiskCustomer => 'Customer has high risk rating',
            self::UnusualPattern => 'Transaction deviates from customer pattern',
            self::ManualReview => 'Flagged for manual review',
            self::HighRiskCountry => 'Customer nationality from high-risk country',
            self::RoundAmount => 'Transaction amount is round number requiring review',
            self::ProfileDeviation => 'Transaction volume exceeds customer profile estimate',
            self::AmlRuleTriggered => 'Automated AML rule triggered for review',
            self::CounterfeitCurrency => 'Counterfeit currency detected in transaction',
            self::RiskScoreEscalation => 'Customer risk score has been escalated',
        };
    }

    /**
     * Get the severity level of this flag type.
     */
    public function severity(): string
    {
        return match ($this) {
            self::SanctionsHit, self::SanctionMatch, self::CounterfeitCurrency => 'critical',
            self::Structuring => 'high',
            self::HighRiskCustomer, self::EddRequired, self::LargeAmount => 'medium',
            default => 'low',
        };
    }

    /**
     * Get the color class for UI display.
     */
    public function color(): string
    {
        return match ($this) {
            self::SanctionsHit, self::SanctionMatch, self::CounterfeitCurrency => 'danger',
            self::Structuring => 'warning',
            self::HighRiskCustomer, self::EddRequired, self::LargeAmount => 'info',
            default => 'secondary',
        };
    }

    /**
     * Get flag types that should put a transaction on hold.
     */
    public static function holdTriggering(): array
    {
        return [
            self::LargeAmount,
            self::EddRequired,
            self::PepStatus,
            self::SanctionMatch,
            self::CounterfeitCurrency,
            self::HighRiskCustomer,
        ];
    }

    /**
     * Get flag types that require compliance officer review.
     */
    public static function requiringComplianceReview(): array
    {
        return [
            self::SanctionsHit,
            self::Structuring,
            self::SanctionMatch,
            self::CounterfeitCurrency,
        ];
    }
}
