<?php

namespace App\Providers;

use App\Events\AlertCreated;
use App\Events\CaseOpened;
use App\Events\CustomerRelationAdded;
use App\Events\CustomerRelationRemoved;
use App\Events\RiskScoreUpdated;
use App\Events\StrDraftAutoGenerated;
use App\Events\StrDraftGenerated;
use App\Events\TransactionCreated;
use App\Listeners\ComplianceEventListener;
use App\Listeners\CustomerRelationListener;
use App\Listeners\TransactionCreatedListener;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event to listener mappings for the application.
     *
     * @var array<class-string, array<int, class-string>>
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        TransactionCreated::class => [
            TransactionCreatedListener::class,
        ],
        AlertCreated::class => [
            ComplianceEventListener::class,
        ],
        CaseOpened::class => [
            ComplianceEventListener::class,
        ],
        StrDraftGenerated::class => [
            ComplianceEventListener::class,
        ],
        StrDraftAutoGenerated::class => [
            [ComplianceEventListener::class, 'handleStrDraftAutoGenerated'],
        ],
        RiskScoreUpdated::class => [
            ComplianceEventListener::class,
        ],
        RiskScoreCalculated::class => [
            ComplianceEventListener::class,
        ],
        CustomerRelationAdded::class => [
            [CustomerRelationListener::class, 'handleAdded'],
        ],
        CustomerRelationRemoved::class => [
            [CustomerRelationListener::class, 'handleRemoved'],
        ],
    ];

    /**
     * Register any events for your application.
     */
    public function boot(): void
    {
        //
    }

    /**
     * Determine if events and listeners should be automatically discovered.
     */
    public function shouldDiscoverEvents(): bool
    {
        return false;
    }
}
